name: Solicitud de Nueva Funci贸n

on:
  issues:
    types:
      - opened
    labels:
      - nueva-funcion

jobs:
  notificar-funcion:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificaci贸n a Slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "隆Nueva solicitud de funci贸n! ",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "隆Nueva solicitud de funci贸n! \n*Issue:* <${{ github.event.issue.html_url }}|#${{ github.event.issue.number }}>\n*T铆tulo:* ${{ github.event.issue.title }}\n*Descripci贸n:* ${{ github.event.issue.body }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
